### PR TITLE
Add .NET Standard 2.0 target framework

### PR DESCRIPTION
**Pull request by bdovaz**
Please add this target framework to minimize dependencies and make it compatible with the Unity 3D game engine which only supports .NET Standard 2.0+.

### CODE REVIEW

**Comment by bdovaz** [comment]
@SteveWilkes It seems to fail because of not having properly configured the .NET SDK (compatible with .NET Core 3.x) in AppVeyor.

**Comment by SteveWilkes** [comment]
Hi,

Thanks very much for this - I'll sort out a release with .NET Standard 2 support and get back to you.

Cheers,

Steve

**Comment by SteveWilkes** [comment]
Closing this PR as I've added a .NET Standard 2.0 target in v1.5, which is now available [on NuGet](https://www.nuget.org/packages/AgileObjects.NetStandardPolyfills).

Thanks!

**Comment by bdovaz** [comment]
Thanks, so now you can address:

https://github.com/agileobjects/ReadableExpressions/pull/82

**Pull request closed without merging**
